csiImage:
  repository: projects.registry.vmware.com/vmware-cloud-director/cloud-director-named-disk-csi-driver
  pullPolicy: IfNotPresent
  tag: "1.6.0"

storageClasses:
  - name: vcd-named-disk-delete
    default: false  
    reclaimPolicy: Delete
    storageProfile: ""
    filesystem: "ext4"
  - name: vcd-named-disk-retain
    default: true
    reclaimPolicy: Retain
    storageProfile: ""
    filesystem: "ext4"

authentication:
  username: ""
  password: ""

vcd:
  host: ""
  org: ""
  vdc: ""
  zone: ""
  vAppName: ""