{{- range .Values.storageClasses }}
---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  {{- if .default }}
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
  {{- end }}
  name: {{ .name }}
provisioner: named-disk.csi.cloud-director.vmware.com
reclaimPolicy: {{ .reclaimPolicy }}
parameters:
  storageProfile: {{ .storageProfile }}
  filesystem: {{ .filesystem }}
{{- end }}