{{- if .Values.vcd.configMap.generate -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: vcloud-csi-configmap
  namespace: {{ .Release.Namespace }}
data:
  vcloud-csi-config.yaml: |
    vcd:
      host: {{ .Values.vcd.host }}
      org: {{ .Values.vcd.org }}
      vdc: {{ .Values.vcd.vdc }}
      vAppName: {{ .Values.vcd.vAppName }}
immutable: true
{{- end -}}
