---
apiVersion: v1
kind: ConfigMap
metadata:
  name: vcloud-capvcd-zones
  namespace: {{ .Release.Namespace }}
data:
  vcloud-cse-zones.yaml: |+
    zoneType: dcgroup
    zones:
    - name: ZONE_NAME
      ovdcName: {{ .Values.vcd.zone }}
---
