---
apiVersion: v1
kind: ConfigMap
metadata:
  name: vcloud-csi-configmap
  namespace: kube-system
data:
  vcloud-csi-config.yaml: |
    vcd:
      host: {{ .Values.host }}
      org: {{ .Values.org }}
      vdc: {{ .Values.vdc }}
      vAppName: {{ .Values.vAppName }}
    clusterid: {{ .Values.clusterid }}
immutable: true
