---
apiVersion: v1
kind: Secret
metadata:
  name: vcloud-basic-auth
  namespace: kube-system
data:
  username: {{ .Values.authentication.username | b64enc }}
  password: {{ .Values.authentication.password | b64enc }}
  refreshToken: ""
