apiVersion: v2
name: vcloud-csi
description: |
  Container Storage Interface (CSI) driver for VMware Cloud Director Named Independent Disks.
  Source: https://github.com/vmware/cloud-director-named-disk-csi-driver
type: application
version: v1.6.0
appVersion: "1.6.0"
icon: https://raw.githubusercontent.com/kubernetes/cloud-provider-vsphere/master/docs/vmware_logo.png
home: https://github.com/clastix/vcloud-csi
sources: ["https://github.com/clastix/vcloud-csi"]

