csiImage:
  repository: projects.registry.vmware.com/vmware-cloud-director/cloud-director-named-disk-csi-driver
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

storageClasses:
  - name: vcd-named-disk-delete
    default: false  
    reclaimPolicy: Delete
    storageProfile: ""
    filesystem: "ext4"

authentication:
  credentialsSecret:
    name: vcloud-basic-auth
    generate: true
  username: ""
  password: ""

vcd:
  configMap:
    name: vcloud-csi-config
    generate: true
  host: ""
  org: ""
  vdc: ""
  zone: ""
  vAppName: ""
